# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-22 01:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(blank=True, help_text='Описание/название фотографии, в случае если она не загрузилась', max_length=255, null=True, verbose_name='Название')),
                ('image', models.ImageField(help_text='Фотография готового проекта', upload_to='media/projects/', verbose_name='Фотография *')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='common_sq_m',
            field=models.FloatField(blank=True, help_text='Общая площадь готового проекта', null=True, verbose_name='Общая площадь, кв.м.'),
        ),
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.DateField(blank=True, help_text='Дата сдачи проекта', null=True, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default='some description', help_text='Подробное описание проекта', verbose_name='Описание *'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='moderation',
            field=models.BooleanField(default=True, help_text='Публикация проекта на сайте', verbose_name='Публикация'),
        ),
        migrations.AddField(
            model_name='project',
            name='price',
            field=models.PositiveIntegerField(blank=True, help_text='Конечная стоимость проекта', null=True, verbose_name='Стоимость'),
        ),
        migrations.AddField(
            model_name='project',
            name='residential_sq_m',
            field=models.FloatField(blank=True, help_text='Жилая площадь проекта', null=True, verbose_name='Жилая площадь, кв.м.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(help_text='Название проекта, отображаемое при открытии', max_length=255, verbose_name='Заголовок *'),
        ),
        migrations.AddField(
            model_name='image',
            name='project',
            field=models.ForeignKey(help_text='Проект к которому фотография относится', on_delete=django.db.models.deletion.CASCADE, to='portfolio.Project', verbose_name='Проект *'),
        ),
    ]
