# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-23 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20180722_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(help_text='Фотография готового проекта', upload_to='projects/', verbose_name='Фотография *'),
        ),
    ]
